### ISSUE TITLE
TypeError Exception.

### ISSUE THREAD

**Issue by klinkin** [keenlabs/KeenClient-Python#12]
My event obj is like this:
<code>{'user_id': 0,
    'updated_by': None,
    'created_at': datetime.datetime(2014, 1, 10, 9, 11, 19, 950883),
    'lon': 37.617633,
    'updated_at': datetime.datetime(2014, 1, 10, 9, 11, 19, 950926),
    'created_by': None,
    'uddi': u'', 
    'radius': 5, 
    'lat': 55.755786, 
    'query': u'\u041a\u043e\u043b\u0431\u0430\u0441\u0430', 'id': 1}</code>

If i try add_event:
<code>Traceback (most recent call last):
  File "manage.py", line 182, in <module>
    manager.run()
  File "/Users/marika/Envs/mcnmapi/lib/python2.7/site-packages/flask_script/**init**.py", line 405, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/marika/Envs/mcnmapi/lib/python2.7/site-packages/flask_script/**init**.py", line 384, in handle
    return handle(app, _positional_args, *_kwargs)
  File "/Users/marika/Envs/mcnmapi/lib/python2.7/site-packages/flask_script/commands.py", line 145, in handle
    return self.run(_args, *_kwargs)
  File "manage.py", line 165, in test_keen
    "search": objs
  File "/Users/marika/Envs/mcnmapi/lib/python2.7/site-packages/keen/client.py", line 129, in add_events
    self.persistence_strategy.batch_persist(events)
  File "/Users/marika/Envs/mcnmapi/lib/python2.7/site-packages/keen/persistence_strategies.py", line 44, in batch_persist
    self.api.post_events(events)
  File "/Users/marika/Envs/mcnmapi/lib/python2.7/site-packages/keen/api.py", line 88, in post_events
    payload = json.dumps(events)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2014, 1, 10, 9, 11, 19, 950883) is not JSON serializable  </code>

**Comment by peplin** [comment]
It'd be really great if we could pass in a custom JSON encoder. Some of our events include datetimes that we want to serialize to ISO-8601 strings, but we have to pre-process them in order to send to this library's post_events function.

**Comment by josephwegner** [comment]
Gonna close this, as it has become quite stale. I'm gonna stick with @sgammon's suggestion, but dropping an `.isoformat()` on the end of the datetime properties.

Fwiw, we also recently added a Datetime Enrichment addon, which may be helpful: https://keen.io/docs/api/#datetime-parser
