### ISSUE TITLE
PoolManager is not importing properly from requests.packages.urllib3.poolmanager

### ISSUE THREAD

**Issue by rebeccastandig** [keenlabs/KeenClient-Python#39]
A user reported this issue when attempting to import the python client:

```
$ pip install keen==0.3.6 
Downloading/unpacking keen==0.3.6 
Downloading keen-0.3.6.tar.gz 
Running setup.py (path:/home/dubizzle/webapps/price_monkey_env/build/keen/setup.py) egg_info for package keen 

Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from keen==0.3.6) 
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /home/dubizzle/webapps/price_monkey_env/lib/python2.7/site-packages (from keen==0.3.6) 
Requirement already satisfied (use --upgrade to upgrade): Padding in /home/dubizzle/webapps/price_monkey_env/lib/python2.7/site-packages (from keen==0.3.6) 
Installing collected packages: keen 
Found existing installation: keen 0.2.3 
Uninstalling keen: 
Successfully uninstalled keen 
Running setup.py install for keen 

Successfully installed keen 
Cleaning up...

$ python 
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2 
Type "help", "copyright", "credits" or "license" for more information. 
>>> import keen 
Traceback (most recent call last): 
File "<stdin>", line 1, in &lt;module&gt; &lt;br&gt; File "/home/dubizzle/webapps/price_monkey_env/local/lib/python2.7/site-packages/keen/__init__.py", line 2, in &amp;lt;module&amp;gt; &amp;lt;br&amp;gt; from keen.client import KeenClient &amp;lt;br&amp;gt; File "/home/dubizzle/webapps/price_monkey_env/local/lib/python2.7/site-packages/keen/client.py", line 6, in &amp;amp;lt;module&amp;amp;gt; &amp;amp;lt;br&amp;amp;gt; from keen.api import KeenApi &amp;amp;lt;br&amp;amp;gt; File "/home/dubizzle/webapps/price_monkey_env/local/lib/python2.7/site-packages/keen/api.py", line 8, in &amp;amp;amp;lt;module&amp;amp;amp;gt; &amp;amp;amp;lt;br&amp;amp;amp;gt; from requests.packages.urllib3.poolmanager import PoolManager &amp;amp;amp;lt;br&amp;amp;amp;gt;ImportError: No module named packages.urllib3.poolmanager&amp;amp;amp;lt;/module&amp;amp;amp;gt;&amp;amp;lt;/module&amp;amp;gt;&amp;lt;/module&amp;gt;&lt;/module&gt;</stdin>
```

From what I can tell from [this issue](https://github.com/mk-fg/python-onedrive/issues/13), which was supposedly fixed almost a year ago, it seems like requests has issues importing urllib3. I suspect if we simply require urllib3 and import PoolManager from there it will fix this. When I looked at the [code base for requests 2.2.1](https://github.com/kennethreitz/requests/tree/33735480f77891754304e7f13e3cdf83aaaa76aa), it looks like they have copied over the code from urllib3 rather than importing it, and I can't tell what version of urllib3 they expect, so I'm confused.

I can just add urllib3 to requirements.txt and test it, but if anyone has any other ideas please let me know!

**Comment by rebeccastandig** [comment]
Uh it just occurred to me that the version of requests we're using was released before that issue was fixed. Perhaps all we have to do is upgrade requests.

**Comment by rebeccastandig** [comment]
We have been unable to reproduce this error.

**Comment by Dareen** [comment]
we have fixed this by adding requests to our requirements file and forcing its version to 2.5.1

**Comment by rebeccastandig** [comment]
Delightful. Thanks for the feedback! We will be releasing a new version with that fix shortly.
