### ISSUE TITLE
CircleCI + KeenClient-Python

### ISSUE THREAD

**Issue by jdunck** [keenlabs/KeenClient-Python#59]
When installing a recent keen python client on CircleCI under python 2.7.9, I ran into an error.

 Circle's 2.7.9 virtualenv is using pip 1.4.1, which is truly ancient, but CircleCI is a pretty popular build environment.  I think an appropriate fix would either be to try/except in the setup.py around parse_requirements, or to document this specific error with the workaround suggestion of upgrading CircleCI's install pip.

I'll comment below with the original build error as well as the workaround that worked for me.

Alternatively, I think this would work around the problem in setup.py:

```
try: 
    install_reqs = parse_requirements('requirements.txt', session=pip.download.PipSession())
except AttributeError:
    # compatibility for pip < 1.5.6 (which CircleCI uses as of 20150401)
    install_reqs = parse_requirements('requirements.txt')
```

**Comment by jdunck** [comment]
Here's the install failure on a vanilla VM of CircleCI w/ python 2.7.9.  Any pip < 1.5 would be similarly affected:

```
(venv-2.7.9)ubuntu@box337:~$ pip --version
pip 1.4.1 from /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages (python 2.7)
(venv-2.7.9)ubuntu@box337:~$ pip install keen
Downloading/unpacking keen
  Downloading keen-0.3.12.tar.gz
  Running setup.py egg_info for package keen
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/ubuntu/virtualenvs/venv-2.7.9/build/keen/setup.py", line 15, in <module>
        install_reqs = parse_requirements('requirements.txt', session=pip.download.PipSession())
    AttributeError: 'module' object has no attribute 'PipSession'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/ubuntu/virtualenvs/venv-2.7.9/build/keen/setup.py", line 15, in <module>

    install_reqs = parse_requirements('requirements.txt', session=pip.download.PipSession())

AttributeError: 'module' object has no attribute 'PipSession'
```

**Comment by jdunck** [comment]
Here's a workaround for anyone running into the failure.  On Circle, you can also specify the pip upgrade in the dependencies:/override: section of a custom circle.yml.

```
(venv-2.7.9)ubuntu@box337:~$ pip install -U pip
Downloading/unpacking pip from https://pypi.python.org/packages/source/p/pip/pip-6.0.8.tar.gz#md5=2332e6f97e75ded3bddde0ced01dbda3
  Downloading pip-6.0.8.tar.gz (1.2MB): 1.2MB downloaded
  Running setup.py egg_info for package pip

    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
Installing collected packages: pip
  Found existing installation: pip 1.4.1
    Uninstalling pip:
      Successfully uninstalled pip
  Running setup.py install for pip

    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
    Installing pip script to /home/ubuntu/virtualenvs/venv-2.7.9/bin
    Installing pip2.7 script to /home/ubuntu/virtualenvs/venv-2.7.9/bin
    Installing pip2 script to /home/ubuntu/virtualenvs/venv-2.7.9/bin
Successfully installed pip
Cleaning up...
(venv-2.7.9)ubuntu@box337:~$ pip install keen
Collecting keen
  Downloading keen-0.3.12.tar.gz
Collecting Padding>=0.4 (from keen)
  Downloading Padding-0.4.tar.gz
Collecting pycrypto==2.6 (from keen)
  Downloading pycrypto-2.6.tar.gz (443kB)
    100% |################################| 446kB 1.1MB/s
Collecting requests>=2.5 (from keen)
  Downloading requests-2.6.0-py2.py3-none-any.whl (469kB)
    100% |################################| 471kB 1.1MB/s
Installing collected packages: requests, pycrypto, Padding, keen

  Running setup.py install for pycrypto
  ...SNIP...
  Running setup.py install for Padding
  Running setup.py install for keen
Successfully installed Padding-0.4 keen-0.3.12 pycrypto-2.6 requests-2.6.0
```

The circle.yml section that would automate the workaround:

```
dependencies:
  override:
    - pip install --upgrade pip
```

**Comment by stroud109** [comment]
Hey @jdunck! Thanks so much for the description and proposed solution -- both make sense. Any chance you could submit a PR? I'll try to get it merged in next week :smile:

**Comment by stroud109** [comment]
Updated in #61
